use_frameworks!

target 'LaunchApplication_Example' do
  pod 'LaunchApplication', :path => '../'

  target 'LaunchApplication_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
